

export const LOGIN = "LOGIN";
export const LOGIN_PENDING = "LOGIN_PENDING";
export const LOGIN_FULFILLED = "LOGIN_FULFILLED";
export const LOGIN_REJECTED = "LOGIN_REJECTED";

export const ADMIN_LOGIN = "ADMIN_LOGIN";
export const ADMIN_LOGIN_PENDING = "ADMIN_LOGIN_PENDING";
export const ADMIN_LOGIN_FULFILLED = "ADMIN_LOGIN_FULFILLED";
export const ADMIN_LOGIN_REJECTED = "ADMIN_LOGIN_REJECTED";
